version: '3'
services:
  api:
    image: 'node:6.9'
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - back-end
    command: /bin/bash -c "npm install && npm run dev"
  web:
    image: 'node:6.9'
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=8080
    networks:
      - front-end
    command: /bin/bash -c "npm install && npm start"
  db:
    image: 'mongo:latest'
    ports:
     - "27117:27017"
    networks:
      - back-end
networks:
  back-end:
  front-end: